release test

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -3,11 +3,10 @@ name: Build and Release
 on:
   push:
     branches:
-      - master
+      - main
   pull_request:
     branches:
-      - master
-  workflow_dispatch: # Allows manual triggering of the workflow
+      - main
 
 jobs:
   build:
@@ -66,24 +65,37 @@ jobs:
           RELEASE_BODY="Release for version ${{ env.VERSION }}."
           
           # Create the release
-          RELEASE_RESPONSE=$(curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+          RESPONSE=$(curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -d '{"tag_name": "'"$TAG_NAME"'", "name": "'"$RELEASE_NAME"'", "body": "'"$RELEASE_BODY"'"}' \
             https://api.github.com/repos/${{ github.repository }}/releases)
           
-          # Extract the release ID
-          RELEASE_ID=$(echo $RELEASE_RESPONSE | jq -r .id)
-          echo "Release created with ID: $RELEASE_ID"
+          # Check if release creation was successful
+          if echo "$RESPONSE" | grep -q "id"; then
+            RELEASE_ID=$(echo $RESPONSE | jq -r .id)
+            echo "Release created successfully with ID: $RELEASE_ID"
+          else
+            echo "Error creating release: $RESPONSE"
+            exit 1
+          fi
 
       # Upload the full JAR
       - name: Upload Full JAR
         run: |
           VERSION=${{ env.VERSION }}
           FILE_PATH="target/Snake-full-$VERSION.jar"
-          curl -XPOST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/zip" --data-binary @"$FILE_PATH" https://uploads.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=Snake-full-$VERSION.jar
+          RELEASE_ID=${{ steps.create_release.outputs.release_id }}
+          
+          curl -XPOST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/zip" \
+          --data-binary @"$FILE_PATH" \
+          https://uploads.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=Snake-full-$VERSION.jar
 
       # Upload the slim JAR
       - name: Upload Slim JAR
         run: |
           VERSION=${{ env.VERSION }}
           FILE_PATH="target/Snake-slim-$VERSION.jar"
-          curl -XPOST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/zip" --data-binary @"$FILE_PATH" https://uploads.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=Snake-slim-$VERSION.jar
+          RELEASE_ID=${{ steps.create_release.outputs.release_id }}
+          
+          curl -XPOST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/zip" \
+          --data-binary @"$FILE_PATH" \
+          https://uploads.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=Snake-slim-$VERSION.jar
